# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7d853a32800335bd2e854b71f05b8ba888e08eb5044b5bf23e87e726096282401c4757e1183be7a15aaab08e2e1c3217e007587b4e51fd285640aaaebb936f3

test:
  secret_key_base: 56c961b1d2b7e0b3da4ceedf7df9fb4d0691eaac8e05650684ee1b30eb9bce7194b2c8d5b158892edbd682ed481d20c822ad309fd1f9ccbcb8a9def282c426fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
